### ISSUE TITLE
Explain templates on parameters page

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/Products.RhaptosCollection#16]
## Overview
Now that we have a significant amount of CCAP and "w/ recipe" templates, Customer Support is beginning to field questions about what these mean.  We need to add some copy to the parameters tab/page in the Legacy editor to explain this.  

![stylesexplanation](https://user-images.githubusercontent.com/7863733/47931893-1b5bcc00-de9e-11e8-91fa-d75b85f31200.png)

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
- [ ] this issue has been moved into the Connexions org with the following metadata:
Milestone: CNX Q4
Estimate: 1 (or another # if different)
Releases: 11-20-2018

**Comment by openstaxalina** [comment]
Confirmed on QA:
![screen shot 2018-11-09 at 3 08 12 pm](https://user-images.githubusercontent.com/7863733/48288331-62633780-e431-11e8-84c7-afede15b5833.png)

**Comment by omehes** [comment]
Reverified in latest build on staging.cnx.org:

{"date": "2018-11-30 13:34:04 CST",
 "webview": "969e07959a31572cdb61fec6f4573b5644d55637 (v0.42.0)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "worried.werewolf v0.67.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.32.1"
}
